print("Napis, na ktere strane je monitor: [top|bottom|left|right|front|back]")
local side = read()
monitor = peripheral.wrap(side)
monitor.setTextScale(1.7)
monitor.clear()
print("Vyhledat hrace:")
local nick = read()
monitor.setCursorPos(1,1)
monitor.setTextColor(colors.gray)
monitor.write("Informace o hraci: ")
monitor.setTextColor(colors.lime)
monitor.write(nick)
monitor.setCursorPos(1,2)
local request = http.get("https://cm.velda.xyz/cmapi/level/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("Level: ")
monitor.setTextColor(colors.red)
monitor.write(request.readAll())
monitor.setCursorPos(1,3)
local request = http.get("https://cm.velda.xyz/cmapi/primary_vip/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("Rank: ")
monitor.setTextColor(colors.red)
monitor.write(request.readAll())
monitor.setCursorPos(1,4)
local request = http.get("https://cm.velda.xyz/cmapi/played_time/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("Played time: ")
monitor.setTextColor(colors.red)
monitor.write(math.floor(request.readAll() + 0,5))
monitor.setTextColor(colors.gray)
monitor.write(" hodin")
monitor.setCursorPos(1,5)
local request = http.get("https://cm.velda.xyz/cmapi/craftcoins/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("CraftCoins: ")
monitor.setTextColor(colors.red)
monitor.write(request.readAll())
monitor.setCursorPos(1,6)
local request = http.get("https://cm.velda.xyz/cmapi/crafttokens/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("CraftTokens: ")
monitor.setTextColor(colors.red)
monitor.write(request.readAll())
monitor.setCursorPos(1,7)
local request = http.get("https://cm.velda.xyz/cmapi/votetokens/"..nick)
monitor.setTextColor(colors.gray)
monitor.write("VoteTokens: ")
monitor.setTextColor(colors.red)
monitor.write(request.readAll())
